#!/usr/bin/env bash
set -euo pipefail

workspace="${1:-$(pwd)}"
source_dir="$workspace/input/original"
target_dir="$workspace/input/markdown"
mkdir -p "$source_dir" "$target_dir"

course_python=''
office_helper="$workspace/tools/import-office.py"
on_demand_receipt="$workspace/tools/on-demand-packages.jsonl"

have() { command -v "$1" >/dev/null 2>&1; }
have pandoc || { echo 'Missing pandoc.' >&2; exit 2; }
have tesseract || { echo 'Missing tesseract.' >&2; exit 2; }
have pdftotext || { echo 'Missing pdftotext (Poppler).' >&2; exit 2; }
have pdftoppm || { echo 'Missing pdftoppm (Poppler).' >&2; exit 2; }

languages="$(tesseract --list-langs 2>/dev/null || true)"
[[ "$languages" == *tha* && "$languages" == *eng* ]] || {
  echo 'Tesseract Thai and English language data are required.' >&2
  exit 2
}

ensure_office_extractor() {
  local kind="$1" probe spec runtime_env
  if [[ -z "$course_python" ]]; then
    runtime_env="$workspace/tools/runtime-env.sh"
    [[ -f "$runtime_env" ]] || { echo 'Missing tools/runtime-env.sh. Run the AI for Research setup again.' >&2; exit 2; }
    # This file is generated by the course installer and points to the machine-local tool root.
    # shellcheck disable=SC1090
    source "$runtime_env"
    course_python="${VIRTUAL_ENV:-}/bin/python"
    [[ -x "$course_python" ]] || { echo 'The course Python is unavailable. Run setup Repair.' >&2; exit 2; }
  fi
  [[ -f "$office_helper" ]] || { echo 'Missing tools/import-office.py. Run setup Repair.' >&2; exit 2; }
  have uv || { echo 'Missing uv. Run setup Repair.' >&2; exit 2; }
  if [[ "$kind" == pptx ]]; then
    probe='import pptx'
    spec='python-pptx>=1.0,<2'
  else
    probe='import openpyxl'
    spec='openpyxl>=3.1,<4'
  fi
  if ! "$course_python" -c "$probe" >/dev/null 2>&1; then
    echo "INSTALL_ON_DEMAND $spec into the course Python environment"
    uv pip install --python "$course_python" "$spec"
  fi
}

count=0
while IFS= read -r -d '' source; do
  filename="$(basename "$source")"
  stem="${filename%.*}"
  extension="${filename##*.}"
  extension="$(printf '%s' "$extension" | tr '[:upper:]' '[:lower:]')"
  target="$target_dir/$filename.md"
  temporary="$(mktemp -d)"
  trap 'rm -rf "$temporary"' EXIT
  extracted="$temporary/extracted.txt"
  extraction_method=direct-copy

  case "$extension" in
    md|txt)
      cp "$source" "$extracted"
      ;;
    docx|odt|rtf|html|htm)
      extraction_method=pandoc-gfm
      pandoc "$source" -t gfm -o "$extracted"
      ;;
    pptx|xlsx)
      ensure_office_extractor "$extension"
      extraction_method="$("$course_python" "$office_helper" "$source" "$extracted" --kind "$extension" --receipt "$on_demand_receipt")"
      ;;
    pdf)
      extraction_method=poppler-pdftotext
      : > "$extracted"
      pdftotext -layout "$source" "$extracted" 2>/dev/null || true
      text_chars="$(tr -d '[:space:]' < "$extracted" 2>/dev/null | wc -c | tr -d ' ')"
      if (( ${text_chars:-0} < 20 )); then
        extraction_method=tesseract-ocr-tha+eng
        : > "$extracted"
        pdftoppm -png -r 300 "$source" "$temporary/page" >/dev/null 2>&1
        while IFS= read -r -d '' page; do
          tesseract "$page" stdout -l tha+eng 2>/dev/null >> "$extracted"
          printf '\n\n' >> "$extracted"
        done < <(find "$temporary" -name 'page-*.png' -print0)
      fi
      ;;
    png|jpg|jpeg|tif|tiff|bmp|webp)
      extraction_method=tesseract-ocr-tha+eng
      tesseract "$source" stdout -l tha+eng 2>/dev/null > "$extracted"
      ;;
    *)
      echo "SKIP unsupported: $filename"
      rm -rf "$temporary"
      trap - EXIT
      continue
      ;;
  esac

  {
    printf '# %s\n\n' "$stem"
    printf '> Source: `%s`  \n' "$filename"
    printf '> Extraction: `%s`  \n' "$extraction_method"
    printf '> Imported automatically. Compare important claims with the original file.\n\n'
    cat "$extracted"
    printf '\n'
  } > "$target"
  echo "CREATED ${target#"$workspace/"}"
  count=$((count + 1))
  rm -rf "$temporary"
  trap - EXIT
done < <(find "$source_dir" -maxdepth 1 -type f -print0)

echo "IMPORT_RESULT files=$count output=input/markdown"
